---
title: "Text Editors"
editor: visual
---

### Local text editors vs. unix text editors

To write your scripts, you can either write via a local text editor and then upload the script to the cluster or you can write/edit a script directly on the command line. It is good practice to always update your scripts on both your local drive copy and on Sedna in order to keep track of changes you have made. Whether you write/edit locally or on sedna is your personal preference, but ensure you keep an updated copy on both locations.

#### Sublime Text

IN PROGRESS

#### vim

IN PROGRESS

### Moving files to and from servers

To move a files, you should use the `scp` command which is generally formatted as follows `scp <path from source> <path to destination>`

To move a file from your local computer to sedna you can use the following script:

```{python}
#| eval: false
scp -P 22 <username>@161.55.52.157:<SEDNA_PATH>/<filename> <LOCAL_PATH>
```

To move a file from sedna to your local computer you can use the following:

```{python}
#| eval: false
scp -P 22 <LOCAL_PATH>\<filename> <username>@sedna.nwfsc2.noaa.gov:<SEDNA_PATH>
```

To move an entire directory you would add the `-r` flag:

```{python}
#| eval: false
scp -P 22 -r <username>@161.55.52.157:<SEDNA_PATH>/<foldername> <LOCAL_PATH>
```
